In [2]:
import tensorflow as tf

In [3]:
tf.constant([[1., 2., 3.], [4., 5., 6.]])

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [4]:
tf.constant(42)

<tf.Tensor: shape=(), dtype=int32, numpy=42>

In [5]:
t = tf.constant([[1., 2., 3.], [4., 5., 6.]])

In [6]:
t[:, 1:]

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 3.],
       [5., 6.]], dtype=float32)>

In [7]:
t[..., 1]

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2., 5.], dtype=float32)>

In [8]:
def huber_fn(y_true, y_pred):
    error = y_true - y_pred
    is_small_error = tf.abs(error) < 1
    squared_loss = tf.square(error) / 2
    linear_loss = tf.abs(error) - 0.5
    return tf.where(is_small_error, squared_loss, linear_loss)

In [11]:
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

housing = fetch_california_housing()
X_train_full, X_test, y_train_full, y_test = train_test_split(
    housing.data, housing.target.reshape(-1, 1), random_state=42)
X_train, X_valid, y_train, y_valid = train_test_split(
    X_train_full, y_train_full, random_state=42)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_valid_scaled = scaler.transform(X_valid)
X_test_scaled = scaler.transform(X_test)

In [13]:
input_shape = X_train.shape[1:]

In [16]:
import keras
input_shape = X_train.shape[1:]

model = keras.models.Sequential([
    keras.layers.Dense(30, activation="selu", kernel_initializer="lecun_normal",
                       input_shape=input_shape),
    keras.layers.Dense(1),
])

In [17]:
model.compile(loss=huber_fn, optimizer="nadam")

In [19]:
model.fit(X_train_scaled, y_train, epochs=10,
          validation_data=(X_valid_scaled, y_valid))

Epoch 1/10
363/363 [==============================] - 0s 841us/step - loss: 0.2037 - val_loss: 0.1929
Epoch 2/10
363/363 [==============================] - 0s 830us/step - loss: 0.1994 - val_loss: 0.1969
Epoch 3/10
363/363 [==============================] - 0s 837us/step - loss: 0.1956 - val_loss: 0.2065
Epoch 4/10
363/363 [==============================] - 0s 860us/step - loss: 0.1931 - val_loss: 0.1908
Epoch 5/10
363/363 [==============================] - 0s 862us/step - loss: 0.1903 - val_loss: 0.1801
Epoch 6/10
363/363 [==============================] - 0s 858us/step - loss: 0.1868 - val_loss: 0.1897
Epoch 7/10
363/363 [==============================] - 0s 827us/step - loss: 0.1850 - val_loss: 0.1840
Epoch 8/10
363/363 [==============================] - 0s 801us/step - loss: 0.1827 - val_loss: 0.1860
Epoch 9/10
363/363 [==============================] - 0s 811us/step - loss: 0.1795 - val_loss: 0.1796
Epoch 10/10
363/363 [==============================] - 0s 773us/step - loss: 0.177